# Generated by Django 6.1 on 2026-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_entraidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="entraidentity",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
